# Generated by Django 6.0.5 on 2026-07-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEnVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sesion', models.CharField(max_length=200)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('nivel_sugerido', models.CharField(default='A1', max_length=10)),
                ('url_zoom_meet', models.URLField(max_length=255)),
                ('capacidad_maxima', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='curso',
        ),
        migrations.AlterField(
            model_name='contenidoeducativo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='academia.curso'),
        ),
        migrations.AlterField(
            model_name='contenidoeducativo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenidoeducativo',
            name='enlace_recurso',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A1', 'Principiante (A1)'), ('A2', 'Elemental (A2)'), ('B1', 'Intermedio (B1)'), ('B2', 'Intermedio Alto (B2)'), ('C1', 'Avanzado (C1)')], default='A1', max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racha_dias', models.IntegerField(default=0)),
                ('nivel_actual', models.CharField(default='A1', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('Gratuito', 'Gratuito'), ('Premium', 'Premium')], default='Gratuito', max_length=20)),
                ('cursos_comprados', models.TextField(blank=True, default='', help_text='IDs de cursos comprados separados por comas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsistenciaClaseVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_reserva', models.CharField(choices=[('Reservado', 'Reservado'), ('Asistio', 'Asistió'), ('Falto', 'Faltó')], default='Reservado', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('clase_vivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academia.claseenvivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_vivas', to='academia.perfilestudiante')),
            ],
            options={
                'unique_together': {('clase_vivo', 'estudiante')},
            },
        ),
        migrations.AddField(
            model_name='claseenvivo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academia.profesor'),
        ),
        migrations.CreateModel(
            name='ProgresoHabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_score', models.IntegerField(default=0)),
                ('speaking_score', models.IntegerField(default=0)),
                ('reading_score', models.IntegerField(default=0)),
                ('writing_score', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='academia.perfilestudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_transaccion', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Completado'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.curso')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EstudiantePerfil',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
