# Generated by Django 6.0.5 on 2026-07-03 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_academico', models.CharField(max_length=50, verbose_name='Periodo (ej. 2026-I)')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Calificación Final')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones o Comentarios del Docente')),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('En proceso', 'En proceso')], default='En proceso', max_length=20, verbose_name='Estado Académico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academia.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academia.perfilestudiante')),
            ],
            options={
                'verbose_name': 'Récord Académico',
                'verbose_name_plural': 'Récords Académicos',
            },
        ),
    ]
