# Generated by Django 6.0.5 on 2026-07-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_recordacademico'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseenvivo',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clases_en_vivo', to='academia.curso'),
            preserve_default=False,
        ),
    ]
