# Generated by Django 6.0.5 on 2026-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_claseenvivo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseenvivo',
            name='esta_activa',
            field=models.BooleanField(default=True),
        ),
    ]
